version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing
  pre_build:
    commands:
      - echo Installing source NPM dependencies.
      - npm install
  build:
    commands:
      - echo Build started
      - echo Compiling the Node.js code
      - npm run build
  post_build:
    commands:
      - echo Build completed on
artifacts:
  files:
    - '**/*'